[package]
name = "newsletter"
version = "0.1.0"
authors = ["Peter Donovan <peter@darkfusion.io>"]
edition = "2018"
license = "MIT"
description = "Simple, convenient email subscription service"
repository = "https://github.com/peter-donovan/newsletter"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
actix-http = "=3.0.0-beta.9"
actix-web = "=4.0.0-beta.8"

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
